### ISSUE TITLE
create() not escaping quotes

### ISSUE THREAD

**Issue by stephen-ta** [node-modli/modli-mysql#12]
A fixture such as

```
categoryQuestionOne: {
    category_id: 1,
    question_id: 1,
    display: '{"frontend":"yes","backend":"no","research":"yes"}',
    page: 1,
    order: 1,
    element_type: 'dropdown'
  }
```

will generate the following insert statement when calling create()

```
INSERT INTO `ta_smart_advisor_categories_questions_test` (`category_id`,`question_id`,`display`,`page`,`order`,`element_type`) VALUES (1,1,"{"frontend":"yes","backend":"no","research":"yes"}",1,1,"dropdown");
```

which causes the query to fail because of the invalid syntax.

**Comment by TomFrost** [comment]
(Pretty please solve this with prepared statements and not by escaping the quotes <3)

**Comment by stephen-ta** [comment]
Ha! Agreed :) Issue for that already exists... https://github.com/node-modli/modli-mysql/issues/11
